import { openDb, q, closeDb } from './src/core/store/db.js';
openDb({ connectionString: process.env.DATABASE_URL!, password: process.env.DATABASE_PASSWORD, max: 2 });
const cols = await q<any>(`select table_name, column_name, data_type from information_schema.columns where table_schema='public' and table_name in ('messages','orders','conversations','settings','products','model_turns') order by table_name, ordinal_position`);
const byT: Record<string,string[]> = {};
for (const c of cols) (byT[c.table_name] ??= []).push(`${c.column_name}:${c.data_type}`);
for (const [t, c] of Object.entries(byT)) console.log(t, '=>', c.join(', '));
const s = await q<any>(`select * from settings limit 1`);
console.log('SETTINGS KEYS', Object.keys(s[0] ?? {}).join(','));
console.log('alias', JSON.stringify(s[0]?.transfer_alias ?? s[0]?.data ?? null).slice(0,500));
await closeDb();
