import { openDb, q, closeDb } from './src/core/store/db.js';
openDb({ connectionString: process.env.DATABASE_URL!, password: process.env.DATABASE_PASSWORD, max: 2 });
const p = await q<any>(`select category, count(*) n, string_agg(name, ' | ' order by name) nombres from products group by 1 order by 1`);
for (const r of p) console.log(`[${r.category}] (${r.n}) ${String(r.nombres).slice(0,220)}`);
const dm = await q<any>(`select delivery_mode, created_by, count(*) n from orders where created_at > '2026-09-06' and created_at < '2026-09-13' group by 1,2 order by 1,2`);
console.log('--- modalidad x quien cargo (semana) ---');
for (const r of dm) console.log(r.delivery_mode, r.created_by, r.n);
const dt = await q<any>(`select delivery_mode, count(*) n, count(*) filter (where delivery_time is null) sin_hora, count(*) filter (where delivery_date is null) sin_fecha from orders where created_at > '2026-09-06' group by 1`);
console.log('--- sin hora / sin fecha ---');
for (const r of dt) console.log(r.delivery_mode, 'n='+r.n, 'sin_hora='+r.sin_hora, 'sin_fecha='+r.sin_fecha);
await closeDb();
